# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YJAMap3D-master' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YJAMap3D-master

  #pod 'AMap3DMap'#运行Demo先打开
  pod 'YJUIKit'


end
